// Provides structured, realistic demonstration data for Dashboard KPIs, attendance analytics, schedules, and events.
import type {
  AttendanceStatusDistribution,
  ClassAttendanceStat,
  DashboardKpiItem,
  RecentActivityItem,
  TodayClassSession,
  UpcomingAgendaEvent,
  WeeklyAttendanceTrend,
} from './dashboard-types';

export const DASHBOARD_KPIS: DashboardKpiItem[] = [
  {
    id: 'kpi-attendance-rate',
    code: '01/KPI',
    label: 'Overall Attendance',
    value: '94.2%',
    change: '+1.8% vs last month',
    changeType: 'positive',
    description: 'Average across active classes',
  },
  {
    id: 'kpi-total-students',
    code: '02/KPI',
    label: 'Total Students',
    value: '184',
    change: '6 class sections',
    changeType: 'neutral',
    description: 'Enrolled in rosters',
  },
  {
    id: 'kpi-due-events',
    code: '03/KPI',
    label: 'Upcoming Events',
    value: '4',
    change: 'Due this week',
    changeType: 'positive',
    description: 'Milestones & exams',
  },
];

export const CLASS_ATTENDANCE_STATS: ClassAttendanceStat[] = [
  {
    classId: 'class-001',
    subjectCode: 'CS101',
    subjectName: 'Introduction to Computing',
    section: 'BSCS-1A',
    enrolledCount: 38,
    totalSessions: 16,
    presentRate: 96.5,
    lateRate: 2.1,
    absentRate: 1.4,
    excusedRate: 0.0,
    status: 'optimal',
  },
  {
    classId: 'class-002',
    subjectCode: 'CS202',
    subjectName: 'Data Structures and Algorithms',
    section: 'BSCS-2A',
    enrolledCount: 34,
    totalSessions: 14,
    presentRate: 93.8,
    lateRate: 3.5,
    absentRate: 2.0,
    excusedRate: 0.7,
    status: 'optimal',
  },
  {
    classId: 'class-003',
    subjectCode: 'IT301',
    subjectName: 'Web Systems and Technologies',
    section: 'BSIT-3B',
    enrolledCount: 31,
    totalSessions: 15,
    presentRate: 91.2,
    lateRate: 5.1,
    absentRate: 2.4,
    excusedRate: 1.3,
    status: 'optimal',
  },
  {
    classId: 'class-004',
    subjectCode: 'MATH201',
    subjectName: 'Discrete Mathematics',
    section: 'BSCS-1B',
    enrolledCount: 36,
    totalSessions: 12,
    presentRate: 86.4,
    lateRate: 7.2,
    absentRate: 4.8,
    excusedRate: 1.6,
    status: 'moderate',
  },
  {
    classId: 'class-005',
    subjectCode: 'PHY101',
    subjectName: 'Physics for Engineers',
    section: 'BSECE-1A',
    enrolledCount: 25,
    totalSessions: 10,
    presentRate: 89.0,
    lateRate: 4.0,
    absentRate: 5.0,
    excusedRate: 2.0,
    status: 'moderate',
  },
  {
    classId: 'class-006',
    subjectCode: 'ENG105',
    subjectName: 'Technical Communications',
    section: 'BSCS-2B',
    enrolledCount: 20,
    totalSessions: 8,
    presentRate: 74.5,
    lateRate: 12.0,
    absentRate: 9.5,
    excusedRate: 4.0,
    status: 'at-risk',
  },
];

export const WEEKLY_ATTENDANCE_TRENDS: WeeklyAttendanceTrend[] = [
  {
    dayName: 'MON',
    dateKey: '2026-08-31',
    presentCount: 92,
    lateCount: 4,
    absentCount: 3,
    excusedCount: 1,
    totalMarked: 100,
    percentage: 92.0,
  },
  {
    dayName: 'TUE',
    dateKey: '2026-09-01',
    presentCount: 68,
    lateCount: 2,
    absentCount: 1,
    excusedCount: 1,
    totalMarked: 72,
    percentage: 94.4,
  },
  {
    dayName: 'WED',
    dateKey: '2026-09-02',
    presentCount: 98,
    lateCount: 3,
    absentCount: 2,
    excusedCount: 1,
    totalMarked: 104,
    percentage: 94.2,
  },
  {
    dayName: 'THU',
    dateKey: '2026-09-03',
    presentCount: 65,
    lateCount: 4,
    absentCount: 2,
    excusedCount: 1,
    totalMarked: 72,
    percentage: 90.3,
  },
  {
    dayName: 'FRI',
    dateKey: '2026-09-04',
    presentCount: 88,
    lateCount: 5,
    absentCount: 4,
    excusedCount: 2,
    totalMarked: 99,
    percentage: 88.9,
  },
];

export const ATTENDANCE_STATUS_DISTRIBUTION: AttendanceStatusDistribution = {
  present: 842,
  late: 62,
  absent: 52,
  excused: 41,
  total: 997,
  presentPercent: 84.5,
  latePercent: 6.2,
  absentPercent: 5.2,
  excusedPercent: 4.1,
};

export const TODAY_CLASS_SESSIONS: TodayClassSession[] = [
  {
    id: 'session-today-01',
    classId: 'class-001',
    subjectCode: 'CS101',
    subjectName: 'Introduction to Computing',
    section: 'BSCS-1A',
    room: 'CL-302',
    startTime: '08:30',
    endTime: '10:00',
    enrolledCount: 38,
    attendanceCompleted: true,
  },
  {
    id: 'session-today-02',
    classId: 'class-002',
    subjectCode: 'CS202',
    subjectName: 'Data Structures and Algorithms',
    section: 'BSCS-2A',
    room: 'LAB-204',
    startTime: '10:30',
    endTime: '12:00',
    enrolledCount: 34,
    attendanceCompleted: true,
  },
  {
    id: 'session-today-03',
    classId: 'class-003',
    subjectCode: 'IT301',
    subjectName: 'Web Systems and Technologies',
    section: 'BSIT-3B',
    room: 'CL-401',
    startTime: '13:30',
    endTime: '15:00',
    enrolledCount: 31,
    attendanceCompleted: false,
  },
  {
    id: 'session-today-04',
    classId: 'class-004',
    subjectCode: 'MATH201',
    subjectName: 'Discrete Mathematics',
    section: 'BSCS-1B',
    room: 'LH-101',
    startTime: '15:30',
    endTime: '17:00',
    enrolledCount: 36,
    attendanceCompleted: false,
  },
];

export const UPCOMING_AGENDA_EVENTS: UpcomingAgendaEvent[] = [
  {
    id: 'event-001',
    title: 'CS101 — Midterm Practical Examination',
    categoryName: 'Exam',
    categoryCode: 'EXAM',
    accentKey: 'SIGNAL_RED',
    eventDate: '2026-09-04',
    startTime: '09:00',
    endTime: '11:00',
    isAllDay: false,
    location: 'Computer Lab 3',
    subjectCode: 'CS101',
    isCompleted: false,
  },
  {
    id: 'event-002',
    title: 'CS202 — Binary Search Tree Assignment Submission',
    categoryName: 'Assignment',
    categoryCode: 'ASG',
    accentKey: 'SIGNAL_AMBER',
    eventDate: '2026-09-05',
    startTime: '23:59',
    endTime: null,
    isAllDay: true,
    location: 'Canvas / Online Portal',
    subjectCode: 'CS202',
    isCompleted: false,
  },
  {
    id: 'event-003',
    title: 'College Faculty Academic Board Meeting',
    categoryName: 'Meeting',
    categoryCode: 'MTG',
    accentKey: 'SIGNAL_BLUE',
    eventDate: '2026-09-07',
    startTime: '14:00',
    endTime: '16:00',
    isAllDay: false,
    location: 'Conference Hall A',
    subjectCode: null,
    isCompleted: false,
  },
  {
    id: 'event-004',
    title: 'IT301 — REST API Milestone Presentation',
    categoryName: 'Activity',
    categoryCode: 'ACT',
    accentKey: 'SIGNAL_PURPLE',
    eventDate: '2026-09-08',
    startTime: '13:30',
    endTime: '15:00',
    isAllDay: false,
    location: 'Room CL-401',
    subjectCode: 'IT301',
    isCompleted: false,
  },
];

export const RECENT_ACTIVITY_ITEMS: RecentActivityItem[] = [
  {
    id: 'act-001',
    type: 'attendance',
    title: 'Attendance saved for CS202 (BSCS-2A)',
    description: '34 students recorded for Sep 2 session: 32 Present, 2 Late.',
    timestamp: '15 minutes ago',
    targetLink: '/dashboard/attendance',
  },
  {
    id: 'act-002',
    type: 'recitation',
    title: 'Recitation marks recorded for CS101',
    description: 'Updated oral participation marks for 12 students in BSCS-1A.',
    timestamp: '1 hour ago',
    targetLink: '/dashboard/activity',
  },
  {
    id: 'act-003',
    type: 'agenda',
    title: 'Scheduled Midterm Examination event',
    description: 'Added CS101 Midterm Practical for Sep 4 at CL-302.',
    timestamp: '3 hours ago',
    targetLink: '/dashboard/agenda',
  },
  {
    id: 'act-004',
    type: 'student',
    title: 'New student added to MATH201',
    description: 'Enrolled Dela Cruz, Juan (2026-0184) to Section BSCS-1B.',
    timestamp: 'Yesterday at 4:30 PM',
    targetLink: '/dashboard/students',
  },
];
